### ISSUE TITLE
Server died! code: 255, signal: 0 (scala.MatchError)

### ISSUE THREAD

**Issue by davefish** [nawforce/apex-assist#6]
Just installed and trying to use `Assist: Show Dependency Graph` results in the following error:

`Command 'Assist: Show Dependency Graph' resulted in an error (command 'apex-assist.dependencyGraph' not found)`

Any ideas how I can figure out what's going wrong?

 I'm getting the following in the Output window:

```
Apex Assist activated
Spawning 'java -Xmx512m -Dfile.encoding=UTF-8 -cp jars/apexlink-2.1.1.jar com.nawforce.apexlink.cmds.Server'
Client: [debug] Sent: {"jsonrpc":"2.0","id":"b22435f3-850b-492a-a0dd-db4b2aa5c8b2","method":"version","params":{}}
Client: [debug] Sent: {"jsonrpc":"2.0","id":"68cde483-e6ed-4b47-9446-fe0b8f3f1c79","method":"open","params":["/Users/dave/workspace/project"]}
Client: [debug] Received: {"jsonrpc":"2.0","id":"b22435f3-850b-492a-a0dd-db4b2aa5c8b2","result":"/Users/dave/.vscode/extensions/kevinjones.apex-assist-1.4.0/jars/apexlink-2.1.1.jar"}
Server ID: /Users/dave/.vscode/extensions/kevinjones.apex-assist-1.4.0/jars/apexlink-2.1.1.jar
Server: [info] Org created in 50480ms with autoFlush = true, build = 4e65fcd53a48b494636558e6fe0e3ca3e74fbf8c
Server: scala.MatchError: [807 677 638 296] (of class com.nawforce.apexparser.ApexParser$ExpressionContext)
Server: 	at com.nawforce.apexlink.cst.Expression$.construct(Expressions.scala:549)
Server: 	at com.nawforce.apexlink.cst.ExpressionStatement$.construct(Statements.scala:526)
Server: 	at com.nawforce.apexlink.cst.Statement$.$anonfun$construct$54(Statements.scala:595)
Server: 	at scala.Option.map(Option.scala:242)
Server: 	at com.nawforce.apexlink.cst.Statement$.$anonfun$construct$53(Statements.scala:595)
Server: 	at scala.Option.orElse(Option.scala:477)
Server: 	at com.nawforce.apexlink.cst.Statement$.construct(Statements.scala:595)
Server: 	at com.nawforce.apexlink.cst.Statement$.$anonfun$construct$15(Statements.scala:532)
Server: 	at scala.collection.immutable.List.flatMap(List.scala:293)
Server: 	at scala.collection.immutable.List.flatMap(List.scala:79)
Server: 	at com.nawforce.apexlink.cst.Statement$.construct(Statements.scala:532)
Server: 	at com.nawforce.apexlink.cst.LazyBlock.createStatements(Statements.scala:87)
Server: 	at com.nawforce.apexlink.cst.LazyBlock.$anonfun$statements$3(Statements.scala:75)
Server: 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
Server: 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
Server: 	at com.nawforce.apexlink.cst.LazyBlock.statements(Statements.scala:73)
Server: 	at com.nawforce.apexlink.cst.LazyBlock.$anonfun$verify$3(Statements.scala:51)
Server: 	at com.nawforce.apexlink.cst.LazyBlock.$anonfun$verify$3$adapted(Statements.scala:50)
Server: 	at com.nawforce.apexlink.cst.BlockVerifyContext.withInnerBlockVerifyContext(VerifyContext.scala:291)
Server: 	at com.nawforce.apexlink.cst.LazyBlock.verify(Statements.scala:50)
Server: 	at com.nawforce.apexlink.types.apex.TriggerDeclaration.$anonfun$validate$5(TriggerDeclaration.scala:103)
Server: 	at com.nawforce.apexlink.types.apex.TriggerDeclaration.$anonfun$validate$1(TriggerDeclaration.scala:101)
Server: 	at com.nawforce.apexlink.types.apex.TriggerDeclaration.validate(TriggerDeclaration.scala:79)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.$anonfun$consumeTriggers$4(StreamDeployer.scala:237)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.$anonfun$consumeTriggers$4$adapted(StreamDeployer.scala:235)
Server: 	at scala.Option.map(Option.scala:242)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.$anonfun$consumeTriggers$3(StreamDeployer.scala:235)
Server: 	at scala.collection.ArrayOps$.flatMap$extension(ArrayOps.scala:959)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.$anonfun$consumeTriggers$2(StreamDeployer.scala:229)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.consumeTriggers(StreamDeployer.scala:229)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.$anonfun$load$1(StreamDeployer.scala:57)
Server: 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
Server: 	at com.nawforce.apexlink.types.platform.PlatformTypes$.withLoadingObserver(PlatformTypes.scala:69)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.load(StreamDeployer.scala:48)
Server: 	at com.nawforce.apexlink.org.StreamDeployer.<init>(StreamDeployer.scala:41)
Server: 	at com.nawforce.apexlink.org.Module.freeze(Module.scala:53)
Server: 	at com.nawforce.apexlink.org.PackageImpl.$anonfun$freeze$1(PackageImpl.scala:49)
Server: 	at com.nawforce.apexlink.org.PackageImpl.$anonfun$freeze$1$adapted(PackageImpl.scala:49)
Server: 	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
Server: 	at com.nawforce.apexlink.org.PackageImpl.freeze(PackageImpl.scala:49)
Server: 	at com.nawforce.apexlink.org.OrgImpl.$anonfun$packages$11(OrgImpl.scala:103)
Server: 	at com.nawforce.apexlink.org.OrgImpl.$anonfun$packages$11$adapted(OrgImpl.scala:103)
Server: 	at scala.collection.immutable.List.foreach(List.scala:333)
Server: 	at com.nawforce.apexlink.org.OrgImpl.$anonfun$packages$1(OrgImpl.scala:103)
Server: 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
Server: 	at com.nawforce.apexlink.org.OrgImpl.<init>(OrgImpl.scala:67)
Server: 	at com.nawforce.apexlink.api.Org$.$anonfun$newOrg$1(Org.scala:145)
Server: 	at com.nawforce.apexlink.api.Org$.newOrg(Org.scala:143)
Server: 	at com.nawforce.apexlink.api.Org$.newOrg(Org.scala:136)
Server: 	at com.nawforce.apexlink.rpc.OrgQueue.<init>(OrgAPIImpl.scala:34)
Server: 	at com.nawforce.apexlink.rpc.OrgQueue$.open(OrgAPIImpl.scala:258)
Server: 	at com.nawforce.apexlink.rpc.OrgAPIImpl.open(OrgAPIImpl.scala:286)
Server: 	at com.nawforce.apexlink.rpc.RPCServer.$anonfun$new$29(RPCServer.scala:34)
Server: 	at scala.Option.map(Option.scala:242)
Server: 	at com.nawforce.apexlink.rpc.RPCServer.$anonfun$new$27(RPCServer.scala:34)
Server: 	at com.nawforce.apexlink.rpc.RPCServer.$anonfun$handleMessage$20(RPCServer.scala:58)
Server: 	at scala.util.Either.fold(Either.scala:189)
Server: 	at com.nawforce.apexlink.rpc.RPCServer.handleMessage(RPCServer.scala:58)
Server: 	at com.nawforce.apexlink.rpc.RPCServer.run(RPCServer.scala:50)
Server: 	at com.nawforce.apexlink.cmds.Server$.main(Server.scala:23)
Server: 	at com.nawforce.apexlink.cmds.Server.main(Server.scala)
Server died! code: 255, signal: 0
```

**Comment by nawforce** [comment]
That has fallen over when parsing a trigger, unfortunately it does not tell us which one. There are some unreleased improvements in this area but for now your best option is probably to try and identify which trigger is causing the problem but that is going to be a bit trail and error.  
Alternatively you might want to wait for the next version which should be available in the next week or so and we will get better debug output from that if the problem persists.

**Comment by nawforce** [comment]
This should be resolved in latest release.
